# Generated by Django 4.2 on 2024-07-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
