# Generated by Django 4.2 on 2024-09-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
    ]
